### ISSUE TITLE
Dynamic component loading

### ISSUE THREAD

**Issue by digizen** [bwu-dart/bwu_polymer_routing#5] opened 2015-01-10 03:31 UTC
I looked through the example source code, and, correct me if I'm wrong, you're loading all the components up-front. Have you given any thoughts on delayed or dynamic loading of components? I'd imagine that with a bigger app, everything loading at once would not be ideal.

**Comment by zoechi** [comment] 2015-01-12 09:49
Thanks @digizen for your interest in bwu_polymer_routing!

As far as I am aware, there is nothing this package can do about it.

Basically you can use Darts deferred loading feature and I'm pretty sure this package doesn't need to be aware of it at all, but the problem is that the Polymer.dart transformer doesn't support deferred loading yet (see http://dartbug.com).

As soon as Polymer.dart supports deferred loading it should work with bwu_polymer_routing.

**Comment by digizen** [comment] 2015-01-21 02:14
@zoechi - thanks for the info! I'm going to work on retooling my Angular project to be a Polymer app with  BWU routing. I've realized that Angular & Polymer together don't make a good story and the Angular team seems to have focused their efforts on Angular 2.0 to the detriment of any serious improvements in Angular.Dart v1.

**Comment by zoechi** [comment] 2015-01-21 10:38
I stopped working with Angular several months ago because the development was too unpredictable and Polymer does most of what I want. The availability of Core- and Paper-elements made it even harder to stick with Angular. I still keep an eye on Angular development because I like it a lot. Maybe there will come other times and things change again, but currently I stick with Polymer.

**Comment by zoechi** [comment] 2015-01-21 10:40
I'll close the issue then. I'll still get notified if you add a comment though. Or just create a new issue if you have further questions.

**Closed by zoechi** 2015-01-21 10:40 UTC
